version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci"
    open-pull-requests-limit: 5

  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      swift-packages:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(swift)"
    open-pull-requests-limit: 5
