#!/usr/bin/env bash

set -euo pipefail
unset BASH_ENV ENV

readonly SCRIPT_PATH="${1:-$(pwd)/.build/debug/mac-sync}"
readonly SCRIPT_RUNNER="${MAC_SYNC_TEST_RUNNER:-}"
TMP_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/mac-sync-editor.XXXXXX")"
readonly TMP_ROOT
readonly TEST_REPO="${TMP_ROOT}/repo"
readonly TEST_MACHINES_REPO="${TMP_ROOT}/machines-repo"
readonly TEST_HOME="${TMP_ROOT}/home"
readonly FAKE_BIN="${TMP_ROOT}/fake-bin"
readonly CODE_ACTION_LOG="${TMP_ROOT}/code-actions.log"
readonly STDOUT_FILE="${TMP_ROOT}/stdout"
readonly STDERR_FILE="${TMP_ROOT}/stderr"

trap 'rm -rf "$TMP_ROOT"' EXIT INT TERM

fail() {
  printf 'editor test failed: %s\n' "$*" >&2
  exit 1
}

assert_file_contains() {
  local file="$1"
  local pattern="$2"

  [[ -f "$file" ]] || fail "missing file: $file"
  grep -F -- "$pattern" "$file" >/dev/null || fail "missing pattern in $file: $pattern"
}

assert_stdout_contains() {
  local pattern="$1"

  grep -F "$pattern" "$STDOUT_FILE" >/dev/null || fail "missing stdout pattern: $pattern"
}

run_mac_sync() {
  local mode="$1"
  shift

  if [[ -n "$SCRIPT_RUNNER" ]]; then
    HOME="$TEST_HOME" \
    MAC_SYNC_REPO="$TEST_REPO" \
    MAC_SYNC_MACHINES_REPO="$TEST_MACHINES_REPO" \
    MAC_SYNC_MACHINE=target \
    MAC_SYNC_DYNAMIC_REFS=0 \
    MAC_SYNC_HOMEBREW=0 \
    MAC_SYNC_SECRETS=0 \
    CODE_FAKE_MODE="$mode" \
    CODE_FAKE_ACTION_LOG="$CODE_ACTION_LOG" \
    PATH="${FAKE_BIN}:$PATH" \
    SCRIPT_COLOUR=off \
      "$SCRIPT_RUNNER" "$SCRIPT_PATH" "$@" >"$STDOUT_FILE" 2>"$STDERR_FILE"
  else
    HOME="$TEST_HOME" \
    MAC_SYNC_REPO="$TEST_REPO" \
    MAC_SYNC_MACHINES_REPO="$TEST_MACHINES_REPO" \
    MAC_SYNC_MACHINE=target \
    MAC_SYNC_DYNAMIC_REFS=0 \
    MAC_SYNC_HOMEBREW=0 \
    MAC_SYNC_SECRETS=0 \
    CODE_FAKE_MODE="$mode" \
    CODE_FAKE_ACTION_LOG="$CODE_ACTION_LOG" \
    PATH="${FAKE_BIN}:$PATH" \
    SCRIPT_COLOUR=off \
      "$SCRIPT_PATH" "$@" >"$STDOUT_FILE" 2>"$STDERR_FILE"
  fi
}

mkdir -p \
  "$FAKE_BIN" \
  "$TEST_REPO/config" \
  "$TEST_MACHINES_REPO/machines/source/editor" \
  "$TEST_HOME"

cat >"$FAKE_BIN/code" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

mode="${CODE_FAKE_MODE:-sync}"

case "$1" in
  --list-extensions)
    case "$mode" in
      sync)
        printf '%s\n' ms-python.python@2026.1.0 redhat.vscode-yaml@1.2.3
        ;;
      diff|install)
        printf '%s\n' ms-python.python@2026.1.0 old.extra@0.1.0
        ;;
      match)
        printf '%s\n' ms-python.python@2026.1.0 streetsidesoftware.code-spell-checker@4.0.0
        ;;
    esac
    ;;
  --uninstall-extension|--install-extension)
    printf '%s %s\n' "$1" "$2" >>"${CODE_FAKE_ACTION_LOG:?CODE_FAKE_ACTION_LOG is not set}"
    ;;
esac
EOF
chmod +x "$FAKE_BIN/code"
git -C "$TEST_REPO" init -b main >/dev/null
git -C "$TEST_REPO" config user.name "mac-sync test"
git -C "$TEST_REPO" config user.email "mac-sync@example.invalid"
git -C "$TEST_MACHINES_REPO" init -b main >/dev/null
git -C "$TEST_MACHINES_REPO" config user.name "mac-sync test"
git -C "$TEST_MACHINES_REPO" config user.email "mac-sync@example.invalid"

cat >"$TEST_REPO/config/sync-paths.txt" <<'EOF'
.bashrc
EOF

: >"$TEST_REPO/config/excludes.txt"
printf 'home bash\n' >"$TEST_HOME/.bashrc"

run_mac_sync sync sync
assert_stdout_contains "updated VS Code extension snapshot: $TEST_MACHINES_REPO/machines/target/editor/vscode-extensions.txt"
assert_file_contains "$TEST_MACHINES_REPO/machines/target/editor/vscode-extensions.txt" "ms-python.python@2026.1.0"
assert_file_contains "$TEST_MACHINES_REPO/machines/target/editor/vscode-extensions.txt" "redhat.vscode-yaml@1.2.3"

cat >"$TEST_MACHINES_REPO/machines/source/editor/vscode-extensions.txt" <<'EOF'
# Generated by mac-sync. Do not edit.
ms-python.python@2026.1.0
streetsidesoftware.code-spell-checker@4.0.0
EOF

run_mac_sync diff editor diff --from source
assert_stdout_contains "VS Code extensions differ from the source snapshot."
assert_stdout_contains "  code --uninstall-extension old.extra"
assert_stdout_contains "  code --install-extension streetsidesoftware.code-spell-checker@4.0.0"

run_mac_sync install editor install --from source
assert_stdout_contains "applied VS Code extensions from $TEST_MACHINES_REPO/machines/source/editor/vscode-extensions.txt"
assert_file_contains "$CODE_ACTION_LOG" "--uninstall-extension old.extra"
assert_file_contains "$CODE_ACTION_LOG" "--install-extension streetsidesoftware.code-spell-checker@4.0.0"
