#!/usr/bin/env bash

set -euo pipefail
unset BASH_ENV ENV

readonly SCRIPT_PATH="${1:-$(pwd)/bin/mac-sync}"
readonly SCRIPT_RUNNER="${MAC_SYNC_TEST_RUNNER:-}"
TMP_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/mac-sync-restore.XXXXXX")"
readonly TMP_ROOT
readonly TEST_REPO="${TMP_ROOT}/repo"
readonly TEST_MACHINES_REPO="${TMP_ROOT}/machines-repo"
readonly TEST_HOME="${TMP_ROOT}/home"
readonly TEST_INSTALL="${TMP_ROOT}/bin/mac-sync"
readonly FAKE_BIN="${TMP_ROOT}/fake-bin"
readonly SYSTEM_GIT="$(command -v git)"

trap 'rm -rf "$TMP_ROOT"' EXIT INT TERM

fail() {
  printf 'restore test failed: %s\n' "$*" >&2
  exit 1
}

assert_file_contents() {
  local file="$1"
  local expected="$2"
  local actual

  [[ -f "$file" ]] || fail "missing file: $file"
  actual="$(cat "$file")"
  [[ "$actual" == "$expected" ]] || fail "unexpected contents in $file: $actual"
}

run_mac_sync() {
  if [[ -n "$SCRIPT_RUNNER" ]]; then
    HOME="$TEST_HOME" \
    MAC_SYNC_REPO="$TEST_REPO" \
    MAC_SYNC_MACHINES_REPO="$TEST_MACHINES_REPO" \
    MAC_SYNC_MACHINE=target \
    MAC_SYNC_INSTALL_PATH="$TEST_INSTALL" \
    MAC_SYNC_DRY_RUN="${MAC_SYNC_DRY_RUN:-0}" \
    MAC_SYNC_HOMEBREW=0 \
    MAC_SYNC_SECRETS=0 \
    MAC_SYNC_SELF_UPDATE=0 \
    PATH="${FAKE_BIN}:$PATH" \
    REAL_GIT="$SYSTEM_GIT" \
    SCRIPT_COLOUR=off \
      "$SCRIPT_RUNNER" "$SCRIPT_PATH" "$@" >"${TMP_ROOT}/stdout" 2>"${TMP_ROOT}/stderr"
  else
    HOME="$TEST_HOME" \
    MAC_SYNC_REPO="$TEST_REPO" \
    MAC_SYNC_MACHINES_REPO="$TEST_MACHINES_REPO" \
    MAC_SYNC_MACHINE=target \
    MAC_SYNC_INSTALL_PATH="$TEST_INSTALL" \
    MAC_SYNC_DRY_RUN="${MAC_SYNC_DRY_RUN:-0}" \
    MAC_SYNC_HOMEBREW=0 \
    MAC_SYNC_SECRETS=0 \
    MAC_SYNC_SELF_UPDATE=0 \
    PATH="${FAKE_BIN}:$PATH" \
    REAL_GIT="$SYSTEM_GIT" \
    SCRIPT_COLOUR=off \
      "$SCRIPT_PATH" "$@" >"${TMP_ROOT}/stdout" 2>"${TMP_ROOT}/stderr"
  fi
}

mkdir -p \
  "$FAKE_BIN" \
  "$TEST_REPO/bin" \
  "$TEST_REPO/config" \
  "$TEST_MACHINES_REPO/machines/source/github-repositories" \
  "$TEST_MACHINES_REPO/machines/source/home/.config/tool" \
  "$TEST_MACHINES_REPO/machines/target/home" \
  "$TEST_HOME/github/existing/.git" \
  "$TEST_HOME"

cat >"$FAKE_BIN/git" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

if [[ "${1:-}" = "clone" ]]; then
  clone_url="$2"
  target="$3"
  mkdir -p "${target}/.git"
  printf '%s\n' "$clone_url" >"${target}/.git-cloned-url"
  exit 0
fi

exec "${REAL_GIT:?}" "$@"
EOF
chmod +x "$FAKE_BIN/git"

cp "$SCRIPT_PATH" "$TEST_REPO/bin/mac-sync"
git -C "$TEST_REPO" init -b main >/dev/null
git -C "$TEST_REPO" config user.name "mac-sync test"
git -C "$TEST_REPO" config user.email "mac-sync@example.invalid"
git -C "$TEST_MACHINES_REPO" init -b main >/dev/null
git -C "$TEST_MACHINES_REPO" config user.name "mac-sync test"
git -C "$TEST_MACHINES_REPO" config user.email "mac-sync@example.invalid"

cat >"$TEST_REPO/config/sync-paths.txt" <<'EOF'
.bashrc
.config/tool
EOF

: >"$TEST_REPO/config/excludes.txt"

cat >"$TEST_MACHINES_REPO/machines/source/dynamic-sync-paths.txt" <<'EOF'
# Generated by mac-sync. Do not edit.
.dynamicrc
EOF

cat >"$TEST_MACHINES_REPO/machines/source/github-repositories/repositories.txt" <<'EOF'
# Generated by mac-sync. Do not edit.
# Format: relative-path<TAB>github-clone-url
alpha	https://github.com/example/alpha.git
group/nested	https://github.com/example/nested.git
existing	https://github.com/example/existing.git
not-github	https://gitlab.com/example/not-github.git
EOF

printf 'repo-bash\n' >"$TEST_MACHINES_REPO/machines/source/home/.bashrc"
printf 'repo-dynamic\n' >"$TEST_MACHINES_REPO/machines/source/home/.dynamicrc"
printf 'repo-setting\n' >"$TEST_MACHINES_REPO/machines/source/home/.config/tool/settings"
touch -t 202401010000 "$TEST_MACHINES_REPO/machines/source/home/.bashrc"
touch -t 202401010000 "$TEST_MACHINES_REPO/machines/source/home/.dynamicrc"
touch -t 202401010000 "$TEST_MACHINES_REPO/machines/source/home/.config/tool/settings"

run_mac_sync restore --from source
assert_file_contents "$TEST_HOME/.bashrc" "repo-bash"
assert_file_contents "$TEST_HOME/.dynamicrc" "repo-dynamic"
assert_file_contents "$TEST_HOME/.config/tool/settings" "repo-setting"
assert_file_contents "$TEST_HOME/github/alpha/.git-cloned-url" "https://github.com/example/alpha.git"
assert_file_contents "$TEST_HOME/github/group/nested/.git-cloned-url" "https://github.com/example/nested.git"
[[ ! -f "$TEST_HOME/github/existing/.git-cloned-url" ]] || fail "existing repo was cloned over"
[[ ! -e "$TEST_HOME/github/not-github" ]] || fail "non-GitHub repo was restored"

printf 'local-newer\n' >"$TEST_HOME/.bashrc"
touch -t 202501010000 "$TEST_HOME/.bashrc"
run_mac_sync restore --from source
assert_file_contents "$TEST_HOME/.bashrc" "local-newer"

run_mac_sync restore --from source --force
assert_file_contents "$TEST_HOME/.bashrc" "repo-bash"

printf 'local-old\n' >"$TEST_HOME/.dynamicrc"
touch -t 202301010000 "$TEST_HOME/.dynamicrc"
printf 'repo-dynamic-newer\n' >"$TEST_MACHINES_REPO/machines/source/home/.dynamicrc"
touch -t 202401010000 "$TEST_MACHINES_REPO/machines/source/home/.dynamicrc"
run_mac_sync restore --from source
assert_file_contents "$TEST_HOME/.dynamicrc" "repo-dynamic-newer"

rm -f "$TEST_HOME/.dynamicrc"
MAC_SYNC_DRY_RUN=1 run_mac_sync restore --from source
[[ ! -e "$TEST_HOME/.dynamicrc" ]] || fail "dry run wrote .dynamicrc"

printf 'target-bash\n' >"$TEST_MACHINES_REPO/machines/target/home/.bashrc"
touch -t 202401010000 "$TEST_MACHINES_REPO/machines/target/home/.bashrc"
rm -f "$TEST_HOME/.bashrc"
run_mac_sync restore
assert_file_contents "$TEST_HOME/.bashrc" "target-bash"

run_mac_sync restore --from SOURCE --force
assert_file_contents "$TEST_HOME/.bashrc" "repo-bash"

run_mac_sync restore --list-machines
grep -F "source" "${TMP_ROOT}/stdout" >/dev/null || fail "missing source machine listing"
grep -F "target (current default)" "${TMP_ROOT}/stdout" >/dev/null || fail "missing default machine listing"
